import Navbar from "@/Components/Navbar";
import Header from "../Components/Header";
import Providers from "../app/Providers";
import "./globals.css";

// export const metadata = {
//   title: "IMDb Clone",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* Header */}
          <Header />
          {/* Navbar */}
          <Navbar />
          {/* SearchBox */}

          {children}
        </Providers>
      </body>
    </html>
  );
}
